{{- if .Values.application }}
{{- if .Values.application.enabled }}
{{- if .Values.application.repoURL }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name | default .Values.namespace }}
  namespace: applications-gitops
  labels:
    team: {{ .Values.team }}
    argocd.argoproj.io/managed-by: applications-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.namespace }}
  source:
    repoURL: {{ .Values.application.repoURL }}
    targetRevision: {{ .Values.application.targetRevision | default "main" }}
    {{- if .Values.application.chart }}
    chart: {{ .Values.application.chart }}
    {{- else }}
    path: {{ .Values.application.path | default "." }}
    {{- end }}
    {{- if eq .Values.application.sourceType "helm" }}
    helm: {}
    {{- else if eq .Values.application.sourceType "kustomize" }}
    kustomize: {}
    {{- else }}
    directory:
      recurse: true
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}
{{- end }}
