{{- if .Values.resourceQuota }}
{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace }}-quota
  namespace: {{ .Values.namespace }}
  labels:
    team: {{ .Values.team }}
    argocd.argoproj.io/managed-by: applications-gitops
spec:
  hard:
    {{- if .Values.resourceQuota.cpu }}
    requests.cpu: {{ .Values.resourceQuota.cpu.requests | quote }}
    limits.cpu: {{ .Values.resourceQuota.cpu.limits | quote }}
    {{- end }}
    {{- if .Values.resourceQuota.memory }}
    requests.memory: {{ .Values.resourceQuota.memory.requests | quote }}
    limits.memory: {{ .Values.resourceQuota.memory.limits | quote }}
    {{- end }}
    {{- if .Values.resourceQuota.storage }}
    requests.storage: {{ .Values.resourceQuota.storage | quote }}
    {{- end }}
    {{- if .Values.resourceQuota.pods }}
    pods: {{ .Values.resourceQuota.pods | quote }}
    {{- end }}
{{- end }}
{{- end }}
