{{- if .Values.adgroup }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.team }}-admin
  namespace: {{ .Values.namespace }}
  labels:
    team: {{ .Values.team }}
    argocd.argoproj.io/managed-by: applications-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: {{ .Values.adgroup }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}